import createRequestingReducer from 'reducers/common/requesting';
import {
  PINBOARD_GEOGRAPHIC_DATA_FETCH_REQUEST_START,
  PINBOARD_GEOGRAPHIC_DATA_FETCH_REQUEST_SUCCESS,
  PINBOARD_GEOGRAPHIC_DATA_FETCH_REQUEST_FAILURE,
} from 'utils/constants';

export default createRequestingReducer(
  PINBOARD_GEOGRAPHIC_DATA_FETCH_REQUEST_START,
  PINBOARD_GEOGRAPHIC_DATA_FETCH_REQUEST_SUCCESS,
  PINBOARD_GEOGRAPHIC_DATA_FETCH_REQUEST_FAILURE,
);
