export const getDefaultSocialGraphOfficersData = () => ([
  {
    'id': 30209,
    'full_name': 'Bennie Watson',
    'rank': 'Police Officer',
    'race': 'Black',
    'birth_year': '1944',
    'unit': {
      'id': 3,
      'unit_name': '002',
      'description': 'District 002',
    },
    'gender': 'M',
    'allegation_count': 10,
    'sustained_count': 0,
    'honorable_mention_count': 3,
    'major_award_count': 0,
    'trr_count': 0,
    'discipline_count': 0,
    'civilian_compliment_count': 0,
    'resignation_date': '2007-07-17',
    'appointed_date': '1991-01-30',
    'percentile_trr': '0.0000',
    'percentile_allegation_civilian': '35.4196',
    'percentile_allegation_internal': '83.0449',
    'honorable_mention_percentile': 68.9444,
  },
  {
    'id': 28805,
    'full_name': 'Charles Toussas',
    'rank': 'Police Officer',
    'race': 'White',
    'birth_year': '1953',
    'unit': {
      'id': 236,
      'unit_name': '765',
      'description': 'Public Housing North',
    },
    'gender': 'M',
    'allegation_count': 123,
    'sustained_count': 5,
    'honorable_mention_count': 0,
    'major_award_count': 0,
    'trr_count': 0,
    'discipline_count': 5,
    'civilian_compliment_count': 0,
    'resignation_date': '2005-02-15',
    'appointed_date': '1981-01-19',
    'percentile_trr': '0.0000',
    'percentile_allegation_civilian': '98.6239',
    'percentile_allegation_internal': '88.4491',
    'honorable_mention_percentile': 0.0,
  },
  {
    'id': 22861,
    'full_name': 'David Portis',
    'rank': 'Sergeant of Police',
    'race': 'Black',
    'birth_year': '1948',
    'unit': {
      'id': 232,
      'unit_name': '715',
      'description': 'Public Housing South',
    },
    'gender': 'M',
    'allegation_count': 11,
    'sustained_count': 1,
    'honorable_mention_count': 0,
    'major_award_count': 0,
    'trr_count': 0,
    'discipline_count': 0,
    'civilian_compliment_count': 0,
    'resignation_date': '1995-12-13',
    'appointed_date': '1970-06-15',
    'honorable_mention_percentile': '0.0000',
  },
  {
    'id': 3663,
    'full_name': 'Donnell Calhoun',
    'rank': 'Police Officer',
    'race': 'Black',
    'birth_year': '1949',
    'unit': {
      'id': 232,
      'unit_name': '715',
      'description': 'Public Housing South',
    },
    'gender': 'M',
    'allegation_count': 39,
    'sustained_count': 5,
    'honorable_mention_count': 0,
    'major_award_count': 0,
    'trr_count': 0,
    'discipline_count': 5,
    'civilian_compliment_count': 0,
    'resignation_date': '2004-08-02',
    'appointed_date': '1978-02-26',
    'percentile_allegation': '97.4780',
    'percentile_allegation_civilian': '87.4780',
    'percentile_allegation_internal': '96.5164',
    'percentile_trr': '96.5164',
    'honorable_mention_percentile': '0.0000',
  },
  {
    'id': 22297,
    'full_name': 'Estella Perez-Stanford',
    'rank': 'Police Officer',
    'badge': '17518',
    'race': 'Hispanic',
    'birth_year': '1968',
    'unit': {
      'id': 5,
      'unit_name': '004',
      'description': 'District 004',
    },
    'gender': 'F',
    'allegation_count': 10,
    'sustained_count': 0,
    'honorable_mention_count': 19,
    'major_award_count': 1,
    'trr_count': 4,
    'discipline_count': 0,
    'civilian_compliment_count': 4,
    'appointed_date': '1997-08-04',
    'percentile_trr': '63.0035',
    'percentile_allegation_civilian': '65.6966',
    'percentile_allegation_internal': '61.1521',
    'honorable_mention_percentile': '73.8267',
  },
  {
    'id': 21194,
    'full_name': 'Eugene Offett',
    'rank': 'Police Officer',
    'badge': '13392',
    'race': 'Black',
    'birth_year': '1964',
    'unit': {
      'id': 112,
      'unit_name': '145',
      'description': 'Traffic Section',
    },
    'gender': 'M',
    'allegation_count': 32,
    'sustained_count': 0,
    'honorable_mention_count': 3,
    'major_award_count': 0,
    'trr_count': 1,
    'discipline_count': 0,
    'civilian_compliment_count': 1,
    'resignation_date': '2016-09-10',
    'appointed_date': '1987-04-13',
    'percentile_trr': '38.9028',
    'percentile_allegation_civilian': '61.9992',
    'percentile_allegation_internal': '0.0000',
    'honorable_mention_percentile': '41.6094',
  },
  {
    'id': 12176,
    'full_name': 'Francis Higgins',
    'rank': 'Sergeant of Police',
    'badge': '1667',
    'race': 'White',
    'birth_year': '1954',
    'unit': {
      'id': 23,
      'unit_name': '022',
      'description': 'District 022',
    },
    'gender': 'M',
    'allegation_count': 65,
    'sustained_count': 4,
    'honorable_mention_count': 17,
    'major_award_count': 0,
    'trr_count': 0,
    'discipline_count': 3,
    'civilian_compliment_count': 3,
    'resignation_date': '2010-11-15',
    'appointed_date': '1981-04-13',
    'percentile_trr': '0.0000',
    'percentile_allegation_civilian': '85.9396',
    'percentile_allegation_internal': '76.8944',
    'honorable_mention_percentile': 75.7087,
  },
  {
    'id': 4881,
    'full_name': 'Gilbert Cobb',
    'rank': 'Police Officer',
    'race': 'Black',
    'birth_year': '1951',
    'unit': {
      'id': 4,
      'unit_name': '003',
      'description': 'District 003',
    },
    'gender': 'M',
    'allegation_count': 47,
    'sustained_count': 7,
    'honorable_mention_count': 2,
    'major_award_count': 0,
    'trr_count': 0,
    'discipline_count': 6,
    'civilian_compliment_count': 0,
    'resignation_date': '2012-01-15',
    'appointed_date': '1978-02-27',
    'percentile_trr': '0.0000',
    'percentile_allegation_civilian': '85.1838',
    'percentile_allegation_internal': '0.0000',
    'honorable_mention_percentile': 0.0,
  },
  {
    'id': 8138,
    'full_name': 'Glenn Evans',
    'rank': 'Lieutenant of Police',
    'badge': '443',
    'race': 'Black',
    'birth_year': '1962',
    'unit': {
      'id': 12,
      'unit_name': '011',
      'description': 'District 011',
    },
    'gender': 'M',
    'allegation_count': 132,
    'sustained_count': 12,
    'honorable_mention_count': 48,
    'major_award_count': 5,
    'trr_count': 21,
    'discipline_count': 12,
    'civilian_compliment_count': 43,
    'appointed_date': '1986-07-14',
    'percentile_trr': '94.8712',
    'percentile_allegation_civilian': '99.6612',
    'percentile_allegation_internal': '61.1521',
    'honorable_mention_percentile': 80.0466,
  },
  {
    'id': 30466,
    'full_name': 'Hardy White',
    'rank': 'Police Officer',
    'race': 'Black',
    'birth_year': '1943',
    'unit': {
      'id': 232,
      'unit_name': '715',
      'description': 'Public Housing South',
    },
    'gender': 'M',
    'allegation_count': 14,
    'sustained_count': 1,
    'honorable_mention_count': 0,
    'major_award_count': 0,
    'trr_count': 0,
    'discipline_count': 1,
    'civilian_compliment_count': 0,
    'resignation_date': '1999-02-05',
    'appointed_date': '1969-11-03',
    'honorable_mention_percentile': 0.0,
  },
  {
    'id': 15956,
    'full_name': 'Isaac Lee',
    'rank': 'Police Officer / Field Training Officer',
    'badge': '10353',
    'race': 'Black',
    'birth_year': '1962',
    'unit': {
      'id': 3,
      'unit_name': '002',
      'description': 'District 002',
    },
    'gender': 'M',
    'allegation_count': 59,
    'sustained_count': 7,
    'honorable_mention_count': 37,
    'major_award_count': 0,
    'trr_count': 7,
    'discipline_count': 6,
    'civilian_compliment_count': 1,
    'resignation_date': '2017-02-14',
    'appointed_date': '1990-03-26',
    'percentile_trr': '75.2071',
    'percentile_allegation_civilian': '96.1830',
    'percentile_allegation_internal': '88.3297',
    'honorable_mention_percentile': 78.342,
  },
  {
    'id': 11580,
    'full_name': 'John Hart',
    'rank': 'Police Officer',
    'race': 'Black',
    'birth_year': '1943',
    'unit': {
      'id': 117,
      'unit_name': '151',
      'description': 'Traffic Enforcement',
    },
    'gender': 'M',
    'allegation_count': 15,
    'sustained_count': 1,
    'honorable_mention_count': 0,
    'major_award_count': 0,
    'trr_count': 0,
    'discipline_count': 1,
    'civilian_compliment_count': 0,
    'resignation_date': '2003-09-15',
    'appointed_date': '1976-03-08',
    'percentile_allegation_civilian': '0.0000',
    'percentile_allegation_internal': '0.0000',
    'honorable_mention_percentile': 0.0,
  },
  {
    'id': 4269,
    'full_name': 'Johnny Cavers',
    'rank': 'Police Officer',
    'badge': '6960',
    'race': 'Black',
    'birth_year': '1963',
    'unit': {
      'id': 3,
      'unit_name': '002',
      'description': 'District 002',
    },
    'gender': 'M',
    'allegation_count': 48,
    'sustained_count': 0,
    'honorable_mention_count': 16,
    'major_award_count': 0,
    'trr_count': 0,
    'discipline_count': 0,
    'civilian_compliment_count': 5,
    'appointed_date': '1991-02-27',
    'percentile_trr': '0.0000',
    'percentile_allegation_civilian': '92.1417',
    'percentile_allegation_internal': '61.1521',
    'honorable_mention_percentile': 68.1146,
  },
  {
    'id': 2171,
    'full_name': 'Joseph Blaye',
    'rank': 'Police Officer / Mounted Patrol Officer',
    'race': 'Black',
    'birth_year': '1947',
    'unit': {
      'id': 38,
      'unit_name': '055',
      'description': 'Mounted Unit',
    },
    'gender': 'M',
    'allegation_count': 5,
    'sustained_count': 0,
    'honorable_mention_count': 2,
    'major_award_count': 0,
    'trr_count': 0,
    'discipline_count': 0,
    'civilian_compliment_count': 1,
    'resignation_date': '2009-01-15',
    'appointed_date': '1977-04-04',
    'percentile_trr': '0.0000',
    'percentile_allegation_civilian': '30.7374',
    'percentile_allegation_internal': '0.0000',
    'honorable_mention_percentile': 55.4155,
  },
  {
    'id': 2675,
    'full_name': 'Matthew Brandon',
    'rank': 'Police Officer',
    'race': 'Black',
    'birth_year': '1951',
    'unit': {
      'id': 232,
      'unit_name': '715',
      'description': 'Public Housing South',
    },
    'gender': 'M',
    'allegation_count': 4,
    'sustained_count': 0,
    'honorable_mention_count': 0,
    'major_award_count': 0,
    'trr_count': 0,
    'discipline_count': 0,
    'civilian_compliment_count': 0,
    'resignation_date': '1994-09-28',
    'appointed_date': '1978-02-27',
    'honorable_mention_percentile': 0.0,
  },
  {
    'id': 31945,
    'full_name': 'Melvin Ector',
    'rank': 'Police Officer',
    'badge': '5083',
    'race': 'Black',
    'birth_year': '1966',
    'unit': {
      'id': 149,
      'unit_name': '189',
      'description': 'Narcotics Division',
    },
    'gender': 'M',
    'allegation_count': 45,
    'sustained_count': 2,
    'honorable_mention_count': 27,
    'major_award_count': 1,
    'trr_count': 0,
    'discipline_count': 2,
    'civilian_compliment_count': 3,
    'appointed_date': '1994-05-31',
    'percentile_trr': '0.0000',
    'percentile_allegation_civilian': '94.1100',
    'percentile_allegation_internal': '61.1521',
    'honorable_mention_percentile': 75.8385,
  },
  {
    'id': 2671,
    'full_name': 'Sean Brandon',
    'rank': 'Police Officer',
    'badge': '18866',
    'race': 'White',
    'birth_year': '1968',
    'unit': {
      'id': 173,
      'unit_name': '311',
      'description': 'Gang Enforcement - Area Central',
    },
    'gender': 'M',
    'allegation_count': 40,
    'sustained_count': 0,
    'honorable_mention_count': 136,
    'major_award_count': 1,
    'trr_count': 16,
    'discipline_count': 0,
    'civilian_compliment_count': 2,
    'appointed_date': '1995-08-07',
    'percentile_trr': '91.2913',
    'percentile_allegation_civilian': '95.0419',
    'percentile_allegation_internal': '61.1521',
    'honorable_mention_percentile': 96.5424,
  },
  {
    'id': 14045,
    'full_name': 'Thomas Kampenga',
    'rank': 'Police Officer as Detective',
    'race': 'White',
    'birth_year': '1949',
    'unit': {
      'id': 208,
      'unit_name': '610',
      'description': 'Detective Area - Central',
    },
    'gender': 'M',
    'allegation_count': 46,
    'sustained_count': 3,
    'honorable_mention_count': 2,
    'major_award_count': 0,
    'trr_count': 0,
    'discipline_count': 3,
    'civilian_compliment_count': 1,
    'resignation_date': '2009-11-15',
    'appointed_date': '1980-09-29',
    'percentile_trr': '0.0000',
    'percentile_allegation_civilian': '30.3789',
    'percentile_allegation_internal': '0.0000',
    'honorable_mention_percentile': 56.7008,
  },
  {
    'id': 12737,
    'full_name': 'Tracy Hughes',
    'rank': 'Police Officer',
    'race': 'Black',
    'birth_year': '1971',
    'unit': {
      'id': 232,
      'unit_name': '715',
      'description': 'Public Housing South',
    },
    'gender': 'F',
    'allegation_count': 4,
    'sustained_count': 1,
    'honorable_mention_count': 0,
    'major_award_count': 0,
    'trr_count': 0,
    'discipline_count': 1,
    'civilian_compliment_count': 0,
    'resignation_date': '2004-09-24',
    'appointed_date': '1995-12-04',
    'percentile_allegation_civilian': '0.0000',
    'percentile_allegation_internal': '89.7816',
    'honorable_mention_percentile': 0.0,
  },
  {
    'id': 24157,
    'full_name': 'William Roberison',
    'rank': 'Police Officer',
    'race': 'Black',
    'birth_year': '1952',
    'unit': {
      'id': 31,
      'unit_name': '045',
      'description': 'District Reinstatement Unit',
    },
    'gender': 'M',
    'allegation_count': 20,
    'sustained_count': 5,
    'honorable_mention_count': 1,
    'major_award_count': 0,
    'trr_count': 0,
    'discipline_count': 5,
    'civilian_compliment_count': 0,
    'resignation_date': '2003-01-15',
    'appointed_date': '1978-12-11',
    'percentile_allegation_civilian': '59.8787',
    'percentile_allegation_internal': '99.3352',
    'honorable_mention_percentile': 0.0,
  },
]);
