export const softBlackColor = '#231F20'; // rgb(35, 31, 32)
export const lightGreyColor = '#D0D2D3';
export const veryLightGreyColor = '#E4E4E4';
export const accentColor = '#005EF4'; // rgb(0, 94, 244)
export const fadedAccentColor = '#C5DAFD'; // rgba(0, 94, 244, 0.2)
export const lighterAccentColor = '#4382F6'; // rgba(0, 94, 244, 0.7)
export const greyColor = '#DFDFDF';
export const darkGreyColor = '#666666';
export const midnightBlueColor = '#0B3168';
export const darkGrayColor = '#A7A7A7';
export const snowColor = '#FBFAFA';
export const concreteColor = '#FAF9F9';
export const darkerGreyColor = '#4A4A4A';
export const whiteSmokeColor = 'rgba(255,255,255, 0.7)';
export const monzaColor = 'rgba(208, 1, 27, 0.1)';
export const subdueAccentColor = '#D3E4FC';
export const subdueAccentTextColor = '#4C8EF8'; // rgb(76, 142, 248)
export const lightSubdueAccentTextColor = 'rgba(0, 94, 244, 0.6)';
/* v2 redesign */
export const wildSandColor = '#F4F4F4';
export const altoColor = '#D8D8D8';
export const codGrayColor = '#1D1D1D'; // rgb(29, 29, 29) story source
export const lightMineShaftColor = 'rgba(38, 38, 38, 0.5)'; // rgba(38, 38, 38, 0.498039) story post date
export const nickelColor = 'rgba(47, 41, 43, 0.7)';
export const mediumBlackColor = 'rgba(0, 0, 0, 0.5)';
export const silverSandColor = 'rgba(34, 31, 31, 0.2)';
export const lightBlackColor = 'rgba(0, 0, 0, 0.15)';
export const whiteTwoColor = '#DBDBDB'; // rgb(219, 219, 219)
export const gainsboroColor = '#DEDEDE';
export const eggPlantColor = '#230D2A';
export const fashionPinkColor = '#D002CD';
export const fashionPinkFadedColor = 'rgba(208, 2, 205, .2)';
export const pinkishWhiteColor = '#FFE8FF';
export const mistyRoseColor = '#F9D2E9';
export const softGreenColor = '#B8E986';
export const tomatoPinkColor = '#F5BAD1';
export const mediumGrayColor = '#9B9B9B';
export const burntOrangeColor = '#BC5800';
export const trueGreenColor = '#13AA00';
export const pinkishGreyColor = '#CCCCCC';
export const black32Color = 'rgba(0, 0, 0, 0.32)';
export const deepBlueColor = '#004DC8';
export const lavenderColor = '#CDE0FC';
export const spindleColor = '#B2D5E9';
export const greyishColor = '#ADADAD'; // rgb(173, 173, 173)
export const coralRedColor = '#DC3747';
export const rajahColor = '#F46937';
export const goldenrodColor = '#F69833';
export const swampGreenColor = '#F0C41B';
export const hippieGreenColor = '#5D924E';
export const hardBlackColor = '#1A1818';
export const veryLightBigStone = 'rgba(22, 43, 59, 0.15)';
export const softGreyColor = '#979797';
export const markerRedColor = '#F9001E';
export const brightOrangeColor = '#FF5F00';
export const brightOrangeTwoColor = '#FF6000'; // rgb(255, 96, 0)
export const dustyOrangeColor = '#F46937';
export const sugarCaneColor = '#F5F4F4'; // rgb(245, 244, 244)
export const darkSilverSandColor = '#B9BFC3';
export const skepticColor = '#CFE7DC';
export const jaggedIceColor = '#BDDBE6';
export const romanticColor = '#FFCFB2';
export const porcelainColor = '#E4E8EB';
export const botticelliColor = '#D4E1EC';
export const galleryColor = '#EFEFEF';
export const lightAltoColor = '#E0E0E0';
export const girlyPink = '#FFE8FF';
export const lightGirlyPink = '#FFEFFF';
export const deepGirlyPink = '#FAD7E9';
export const ultraGirlyPink = '#D518d2';
export const eyeCandyPink = '#FFEFFE';
export const smokeGray = '#9F9F9F';
export const clayGray = '#8F8F8F'; // rgb(143, 143, 143)
export const glitterColor = '#E1EBFD';
export const lightBlue = '#1775F1';
export const hawkesBlue = '#CCDFFD'; // rgb(204, 223, 253)
export const bostonRed = '#CC0000';
export const linenColor = '#FDFAF2';
export const cashGreenColor = '#499C21';
export const champagneColor = '#FBE2D4'; // rgb(251, 226, 212)
export const scarletColor = '#FF1F00'; // rgb(255, 31, 0)
export const darkSlateGrayColor = '#464243';
export const darkSapphireBlue = '#556080';
export const boulderColor = '#767676';
export const azaleaColor = '#F5CCCC';
export const athensGray = '#EDEDEE';
export const japaneseLaurelColor = '#236C00';
export const sproutColor = '#C7DFBB';
export const sharkColor = '#28292F';

export const sanFranciscoTextFamily = '"San Francisco Text", sans-serif';
export const minionProFamily = '"Minion Pro Regular", sans-serif';

export const sidebarWidth = 320;

export const searchPreviewPaneWidth = 320;
