export const softBlackColor = '#231F20'; // rgb(35, 31, 32)
export const lightGreyColor = '#D0D2D3';
export const veryLightGreyColor = '#E4E4E4';
export const accentColor = '#005EF4'; // rgb(0, 94, 244)
export const greyColor = '#DFDFDF';
export const darkGreyColor = '#666666';
export const midnightBlueColor = '#0B3168';
export const darkGrayColor = '#A7A7A7';
export const snowColor = '#FBFAFA';
export const darkerGreyColor = '#4A4A4A';
export const whiteSmokeColor = 'rgba(255,255,255, 0.7)';
export const monzaColor = 'rgba(208, 1, 27, 0.1)';
export const subdueAccentColor= '#D3E4FC';
export const subdueAccentTextColor = 'rgba(0, 94, 244, 0.7)';
export const lightSubdueAccentTextColor = 'rgba(0, 94, 244, 0.6)';
/* v2 redesign */
export const wildSandColor = '#F4F4F4';
export const altoColor = '#D8D8D8';
export const codGrayColor = '#1D1D1D'; // rgb(29, 29, 29) story source
export const lightMineShaftColor = 'rgba(38, 38, 38, 0.5)'; // rgba(38, 38, 38, 0.498039) story post date
export const nickelColor = 'rgba(47, 41, 43, 0.7)';
export const mediumBlackColor = 'rgba(0, 0, 0, 0.5)';
export const silverSandColor = 'rgba(34, 31, 31, 0.2)';
export const lightBlackColor = 'rgba(0, 0, 0, 0.15)';
export const whiteTwoColor = '#DBDBDB';
export const eggPlantColor = '#230D2A';
export const fashionPinkColor = '#D002CD';
export const fashionPinkFadedColor = 'rgba(208, 2, 205, .2)';
export const pinkishWhiteColor = '#FFE8FF';
export const mistyRoseColor = '#F9D2E9';
export const softGreenColor = '#B8E986';
export const tomatoPinkColor = '#F5BAD1';
export const mediumGrayColor = '#9B9B9B';
export const burntOrangeColor = '#BC5800';
export const trueGreenColor = '#13AA00';
export const pinkishGreyColor = '#CCCCCC';
export const black32Color = 'rgba(0, 0, 0, 0.32)';
export const deepBlueColor = '#004DC8';
export const lavenderColor = '#CDE0FC';
export const spindleColor = '#B2D5E9';
export const greyishColor = '#ADADAD';
export const coralRedColor = '#DC3747';
export const rajahColor = '#F46937';
export const goldenrodColor = '#F69833';
export const swampGreenColor = '#F0C41B';
export const hippieGreenColor = '#5D924E';
export const hardBlackColor = '#1A1818';
export const veryLightBigStone = 'rgba(22, 43, 59, 0.15)';
export const softGreyColor = '#979797';
export const markerRedColor = '#F9001E';
export const brightOrangeColor = '#FF5F00';
export const brightOrangeTwoColor = '#FF6000';
export const dustyOrangeColor = '#F46937';
export const sugarCaneColor = '#F5F4F4';
export const darkSilverSandColor = '#B9BFC3';
export const skepticColor = '#CFE7DC';
export const jaggedIceColor = '#BDDBE6';
export const romanticColor = '#FFCFB2';
export const porcelainColor = '#E4E8EB';
export const botticelliColor = '#D4E1EC';
export const galleryColor = '#EFEFEF';
export const lightAltoColor = '#E0E0E0';

export const sanFranciscoTextFamily = '"San Francisco Text", sans-serif';
export const minionProFamily = '"Minion Pro Regular",sans-serif';
