import { get } from 'actions/common/async-action';


export const FEATURED_STORIES_REQUEST_START = 'FEATURED_STORIES_REQUEST_START';
export const FEATURED_STORIES_REQUEST_SUCCESS = 'FEATURED_STORIES_REQUEST_SUCCESS';
export const FEATURED_STORIES_REQUEST_FAILURE = 'FEATURED_STORIES_REQUEST_FAILURE';

export const STORIES_API_URL = 'stories/';

export const requestStories = get(
  STORIES_API_URL,
  [FEATURED_STORIES_REQUEST_START, FEATURED_STORIES_REQUEST_SUCCESS, FEATURED_STORIES_REQUEST_FAILURE]
);
