import { get, authenticatedPatch } from 'actions/common/async-action';


export const STORIES_REQUEST_START = 'STORIES_REQUEST_START';
export const STORIES_REQUEST_SUCCESS = 'STORIES_REQUEST_SUCCESS';
export const STORIES_REQUEST_FAILURE = 'STORIES_REQUEST_FAILURE';

export const STORIES_API_URL = 'http://private-12e3f0-cpdp.apiary-mock.com/reports/';

export const requestStories = get(
  STORIES_API_URL,
  [STORIES_REQUEST_START, STORIES_REQUEST_SUCCESS, STORIES_REQUEST_FAILURE]
);


export const LOAD_MORE_STORIES_REQUEST_START = 'LOAD_MORE_STORIES_REQUEST_START';
export const LOAD_MORE_STORIES_REQUEST_SUCCESS = 'LOAD_MORE_STORIES_REQUEST_SUCCESS';
export const LOAD_MORE_STORIES_REQUEST_FAILURE = 'LOAD_MORE_STORIES_REQUEST_FAILURE';

export const loadMoreStories = (nextUrl) => {
  return get(
    nextUrl,
    [LOAD_MORE_STORIES_REQUEST_START, LOAD_MORE_STORIES_REQUEST_SUCCESS, LOAD_MORE_STORIES_REQUEST_FAILURE]
  )();
};

export const UPDATE_STORY_REQUEST_START = 'UPDATE_STORY_REQUEST_START';
export const UPDATE_STORY_REQUEST_SUCCESS = 'UPDATE_STORY_REQUEST_SUCCESS';
export const UPDATE_STORY_REQUEST_FAILURE = 'UPDATE_STORY_REQUEST_FAILURE';

export const updateReport = (id, data) => (authenticatedPatch(
  `${STORIES_API_URL}${id}`,
  [UPDATE_STORY_REQUEST_START, UPDATE_STORY_REQUEST_SUCCESS, UPDATE_STORY_REQUEST_FAILURE]
  )(data)
);
