import { createAction } from 'redux-actions';

import { get } from 'actions/common/async-action';

import {
  OFFICER_URL, OFFICER_TIMELINE_MINIMAP_REQUEST_START, OFFICER_TIMELINE_MINIMAP_REQUEST_SUCCESS,
  OFFICER_TIMELINE_MINIMAP_REQUEST_FAILURE, OFFICER_TIMELINE_FLIP_SORT_ORDER, OFFICER_TIMELINE_ITEMS_REQUEST_START,
  OFFICER_TIMELINE_ITEMS_REQUEST_SUCCESS, OFFICER_TIMELINE_ITEMS_REQUEST_FAILURE
} from 'utils/constants';


export const fetchMinimap = offficerId => (get(
  `${OFFICER_URL}${offficerId}/timeline-minimap/`,
  [OFFICER_TIMELINE_MINIMAP_REQUEST_START,
   OFFICER_TIMELINE_MINIMAP_REQUEST_SUCCESS,
   OFFICER_TIMELINE_MINIMAP_REQUEST_FAILURE]
)());

export const fetchTimelineItems = offficerId => get(
  `${OFFICER_URL}${offficerId}/timeline-items/`,
  [OFFICER_TIMELINE_ITEMS_REQUEST_START,
   OFFICER_TIMELINE_ITEMS_REQUEST_SUCCESS,
   OFFICER_TIMELINE_ITEMS_REQUEST_FAILURE]
);

export const flipSortOrder = createAction(OFFICER_TIMELINE_FLIP_SORT_ORDER);
