import * as constants from 'utils/constants';

export const getCrawlersData = () => ({
  count: 25,
  next: `${constants.CRAWLERS_API_URL}?limit=20&offset=20`,
  previous: null,
  results: [
    {
      'id': 111,
      'crawler_name': 'SUMMARY_REPORTS_COPA',
      'num_documents': 284,
      'num_new_documents': 0,
      'recent_run_at': '2019-02-20',
      'num_successful_run': 12,
      'log_url': 'https://lvh.me/cpdp-crawler-logs-develop/summary_reports_copa-2019-02-27-100330.txt'
    },
    {
      'id': 110,
      'crawler_name': 'SUMMARY_REPORTS_COPA',
      'num_documents': 284,
      'num_new_documents': 0,
      'recent_run_at': '2019-02-20',
      'num_successful_run': 11,
    },
    {
      'id': 109,
      'crawler_name': 'SUMMARY_REPORTS_COPA',
      'num_documents': 284,
      'num_new_documents': 0,
      'recent_run_at': '2019-02-20',
      'num_successful_run': 10,
    },
    {
      'id': 108,
      'crawler_name': 'SUMMARY_REPORTS_COPA',
      'num_documents': 284,
      'num_new_documents': 0,
      'recent_run_at': '2019-02-20',
      'num_successful_run': 9,
    },
    {
      'id': 107,
      'crawler_name': 'SUMMARY_REPORTS_COPA',
      'num_documents': 284,
      'num_new_documents': 0,
      'recent_run_at': '2019-02-20',
      'num_successful_run': 8,
    },
    {
      'id': 106,
      'crawler_name': 'SUMMARY_REPORTS_COPA',
      'num_documents': 284,
      'num_new_documents': 0,
      'recent_run_at': '2019-02-20',
      'num_successful_run': 7,
    },
    {
      'id': 105,
      'crawler_name': 'PORTAL_COPA',
      'num_documents': 3143,
      'num_new_documents': 0,
      'recent_run_at': '2019-02-20',
      'num_successful_run': 6,
    },
    {
      'id': 104,
      'crawler_name': 'PORTAL_COPA',
      'num_documents': 3143,
      'num_new_documents': 36,
      'recent_run_at': '2019-02-20',
      'num_successful_run': 5,
    },
    {
      'id': 103,
      'crawler_name': 'SUMMARY_REPORTS_COPA',
      'num_documents': 284,
      'num_new_documents': 267,
      'recent_run_at': '2019-02-20',
      'num_successful_run': 6,
    },
    {
      'id': 102,
      'crawler_name': 'SUMMARY_REPORTS_COPA',
      'num_documents': 1173,
      'num_new_documents': 0,
      'recent_run_at': '2019-02-15',
      'num_successful_run': 5,
    },
    {
      'id': 101,
      'crawler_name': 'SUMMARY_REPORTS_COPA',
      'num_documents': 1173,
      'num_new_documents': 17,
      'recent_run_at': '2019-02-15',
      'num_successful_run': 4,
    },
    {
      'id': 100,
      'crawler_name': 'SUMMARY_REPORTS_COPA',
      'num_documents': 1173,
      'num_new_documents': 17,
      'recent_run_at': '2019-02-14',
      'num_successful_run': 3,
    },
    {
      'id': 99,
      'crawler_name': 'SUMMARY_REPORTS_COPA',
      'num_documents': 1173,
      'num_new_documents': 17,
      'recent_run_at': '2019-02-14',
      'num_successful_run': 2,
    },
    {
      'id': 98,
      'crawler_name': 'SUMMARY_REPORTS_COPA',
      'num_documents': 1174,
      'num_new_documents': 9,
      'recent_run_at': '2019-02-14',
      'num_successful_run': 1,
    },
    {
      'id': 97,
      'crawler_name': 'PORTAL_COPA',
      'num_documents': 3107,
      'num_new_documents': 0,
      'recent_run_at': '2018-12-24',
      'num_successful_run': 4,
    },
    {
      'id': 96,
      'crawler_name': 'PORTAL_COPA',
      'num_documents': 3107,
      'num_new_documents': 0,
      'recent_run_at': '2018-12-24',
      'num_successful_run': 3,
    },
    {
      'id': 95,
      'crawler_name': 'PORTAL_COPA',
      'num_documents': 3107,
      'num_new_documents': 2,
      'recent_run_at': '2018-12-24',
      'num_successful_run': 2,
    },
    {
      'id': 94,
      'crawler_name': 'PORTAL_COPA',
      'num_documents': 3105,
      'num_new_documents': 1336,
      'recent_run_at': '2018-12-21',
      'num_successful_run': 1,
    },
    {
      'id': 93,
      'crawler_name': 'DOCUMENTCLOUD',
      'num_documents': 2382,
      'num_new_documents': 0,
      'recent_run_at': '2018-12-17',
      'num_successful_run': 7,
    },
    {
      'id': 92,
      'crawler_name': 'DOCUMENTCLOUD',
      'num_documents': 2382,
      'num_new_documents': 1146,
      'recent_run_at': '2018-12-14',
      'num_successful_run': 6,
    },
  ]
});

export const getNextCrawlersData = () => ({
  count: 25,
  next: null,
  previous: 'http://localhost:8000/api/v2/document-crawlers/?limit=20',
  results: [
    {
      'id': 91,
      'crawler_name': 'DOCUMENTCLOUD',
      'num_documents': 1236,
      'num_new_documents': 0,
      'recent_run_at': '2018-12-03',
      'num_successful_run': 5,
    },
    {
      'id': 90,
      'crawler_name': 'DOCUMENTCLOUD',
      'num_documents': 1236,
      'num_new_documents': 0,
      'recent_run_at': '2018-12-02',
      'num_successful_run': 4,
    },
    {
      'id': 89,
      'crawler_name': 'DOCUMENTCLOUD',
      'num_documents': 1236,
      'num_new_documents': 0,
      'recent_run_at': '2018-12-01',
      'num_successful_run': 3,
    },
    {
      'id': 88,
      'crawler_name': 'DOCUMENTCLOUD',
      'num_documents': 1236,
      'num_new_documents': 1,
      'recent_run_at': '2018-11-30',
      'num_successful_run': 2,
    },
    {
      'id': 87,
      'crawler_name': 'DOCUMENTCLOUD',
      'num_documents': 1235,
      'num_new_documents': 0,
      'recent_run_at': '2018-11-29',
      'num_successful_run': 1,
    },
  ]
});

