import { RichTextFieldFactory } from '../../../src/js/utils/test/factories/field';

export const timelineItems = [
  {
    'unit_name': '007',
    kind: 'AWARD',
    'unit_description': 'District 007',
    rank: 'Police Officer',
    date: '2006-03-01',
    'award_type': 'Honorable Mention',
  },
  {
    'trr_id': 1,
    'unit_name': '007',
    kind: 'FORCE',
    taser: true,
    'unit_description': 'District 007',
    rank: 'Police Officer',
    date: '2005-12-17',
    'firearm_used': false,
  },
  {
    'trr_id': 2,
    'unit_name': '007',
    kind: 'FORCE',
    taser: false,
    'unit_description': 'District 007',
    rank: 'Police Officer',
    date: '2005-03-17',
    'firearm_used': false,
  },
  {
    'unit_name': '007',
    kind: 'UNIT_CHANGE',
    'unit_description': 'District 007',
    rank: 'Police Officer',
    date: '2005-01-07',
  },
  {
    'trr_id': 3,
    'unit_name': '153',
    kind: 'FORCE',
    taser: false,
    'unit_description': 'Mobile Strike Force',
    rank: 'Police Officer',
    date: '2004-12-17',
    'firearm_used': true,
  },
  {
    category: 'Illegal Search',
    'unit_name': '153',
    kind: 'CR',
    subcategory: 'Search Of Premise Without Warrant',
    crid: '294088',
    'unit_description': 'Mobile Strike Force',
    rank: 'Police Officer',
    date: '2003-11-26',
    coaccused: 8,
    finding: 'Exonerated',
    outcome: 'No Action Taken',
    attachments: [
      {
        url: 'https://www.documentcloud.org/documents/3518950-CRID-294088-CR.html',
        'preview_image_url': 'https://assets.documentcloud.org/documents/3518950/pages/CRID-294088-CR-p1-normal.gif',
        title: 'CRID 294088 CR',
        'file_type': 'document',
      },
      {
        url: 'https://player.vimeo.com/video/165206078',
        title: 'Video Clip',
        'file_type': 'video',
      },
      {
        url: 'https://w.soundcloud.com/player/?url=https%3A//api.soundcloud.com/tracks/262463136&amp',
        title: 'Audio Clip',
        'file_type': 'audio',
      },
    ],
  },
  {
    category: 'Criminal Misconduct',
    'unit_name': '153',
    kind: 'CR',
    subcategory: 'Theft',
    crid: '260131',
    'unit_description': 'Mobile Strike Force',
    rank: 'Police Officer',
    date: '2003-02-17',
    coaccused: 4,
    finding: 'Sustained',
    outcome: 'No Action Taken',
    attachments: [
      {
        url: 'https://w.soundcloud.com/player/?url=https%3A//api.soundcloud.com/tracks/262463125&amp',
        title: 'Audio Clip',
        'file_type': 'audio',
      },
      {
        url: 'https://player.vimeo.com/video/165213573',
        title: 'Video Clip',
        'file_type': 'video',
      },
      {
        url: 'https://www.documentcloud.org/documents/3518954-CRID-299780-CR.html',
        'preview_image_url': 'https://assets.documentcloud.org/documents/3518954/pages/CRID-299780-CR-p1-normal.gif',
        title: 'CRID 294088 CR',
        'file_type': 'document',
      },
    ],
  },
  {
    'unit_name': '153',
    kind: 'UNIT_CHANGE',
    'unit_description': 'Mobile Strike Force',
    rank: 'Police Officer',
    date: '2000-04-28',
  },
  {
    'unit_name': '153',
    kind: 'RANK_CHANGE',
    'unit_description': 'Mobile Strike Force',
    rank: 'Police Officer',
    date: '2000-04-28',
  },
  {
    'unit_name': '044',
    kind: 'JOINED',
    'unit_description': 'Recruit Training Section',
    rank: 'Detective',
    date: '2000-02-05',
  },
  {
    date: '2000-08-06',
    kind: 'LAWSUIT',
    rank: 'Detective',
    'unit_description': 'Recruit Training Section',
    'unit_name': '044',
    'case_no': '00-L-5230',
    'primary_cause': 'Excessive force, Racial epithets',
    attachments: [
      {
        title: 'Phone subject information organization off important.',
        url: 'https://assets.documentcloud.org/documents/6246754/CRID-1086093-CR-COPA-Summary-Report.pdf',
        'preview_image_url': 'https://assets.documentcloud.org/documents/6246754/pages/CRID.gif',
        'file_type': '',
        'id': '95637',
      },
    ],
  },
];

export const officerData = {
  'id': 1,
  'full_name': 'Bernadette Kelly',
  'unit': {
    'id': 1,
    'unit_name': '001',
    'description': 'District 001',
  },
  'date_of_appt': '2015-09-23',
  'rank': 'Police Officer',
  'race': 'White',
  'badge': '12345',
  'historic_badges': ['54321', '56789'],
  'gender': 'Male',
  'birth_year': 1963,
  'allegation_count': 1,
  'percentile_allegation': '2.0000',
  'percentile_trr': '7.9000',
  'trr_count': '5',
  'major_award_count': 19,
  'honorable_mention_count': 3,
  'sustained_count': 4,
  'discipline_count': 5,
  'civilian_compliment_count': 6,
  'total_lawsuit_settlements': '10000000.00',
  'current_salary': 100000,
  'honorable_mention_percentile': '79.8700',
  'percentiles': [
    {
      'id': 1,
      'year': 2001,
      'percentile_trr': '0.049',
      'percentile_allegation': '43.233',
    },
    {
      'id': 1,
      'year': 2002,
      'percentile_allegation': '43.233',
      'percentile_allegation_civilian': '0.3',
      'percentile_allegation_internal': '0.023',
    },
    {
      'id': 1,
      'year': 2012,
      'percentile_trr': '0.049',
      'percentile_allegation': '43.233',
      'percentile_allegation_civilian': '0.3',
      'percentile_allegation_internal': '0.023',
    },
    {
      'id': 1,
      'year': 2013,
      'percentile_trr': '0.049',
      'percentile_allegation': '43.233',
      'percentile_allegation_civilian': '22.10',
      'percentile_allegation_internal': '0.023',
    },
    {
      'id': 1,
      'year': 2014,
      'percentile_trr': '0.049',
      'percentile_allegation': '43.233',
      'percentile_allegation_civilian': '10.10',
      'percentile_allegation_internal': '0.023',
    },
    {
      'id': 1,
      'year': 2015,
      'percentile_trr': '66.046',
      'percentile_allegation': '43.233',
      'percentile_allegation_civilian': '75.065',
      'percentile_allegation_internal': '0.022',
    },
    {
      'id': 1,
      'year': 2016,
      'percentile_trr': '66.044',
      'percentile_allegation': '32.102',
      'percentile_allegation_civilian': '59.468',
      'percentile_allegation_internal': '0.021',
    },
    {
      'id': 1,
      'year': 2017,
      'percentile_allegation': '32.102',
    },
  ],
};

export const coaccusalsData = [{
  id: 2,
  'full_name': 'John Kelly',
  'complaint_count': 2,
  'sustained_count': 1,
  race: 'White',
  gender: 'Male',
  'birth_year': 1950,
  'coaccusal_count': 2,
  'rank': 'Police Officer',
  'percentile_allegation': '95.0000',
  'percentile_allegation_civilian': '92.0000',
  'percentile_allegation_internal': '91.0000',
  'percentile_trr': '90.0000',
}, {
  id: 3,
  'full_name': 'Jerome Finnigan',
  'complaint_count': 1,
  'sustained_count': 1,
  race: 'Black',
  gender: 'Male',
  'birth_year': 1970,
  'coaccusal_count': 1,
  'rank': 'Detective',
  'percentile_allegation': '99.0000',
  'percentile_allegation_civilian': '72.0000',
  'percentile_allegation_internal': '81.0000',
  'percentile_trr': '80.0000',
}];

export const noPercentileOfficerData = {
  'id': 2,
  'full_name': 'John Kelly',
  'unit': {
    'id': 1,
    'unit_name': '001',
    'description': 'District 001',
  },
  'date_of_appt': '2015-09-23',
  'rank': 'NA',
  'race': 'White',
  'badge': '12345',
  'gender': 'Male',
  'birth_year': 1963,
  'allegation_count': 1,
  'percentile_allegation': '2.0000',
  'honorable_mention_count': 3,
  'sustained_count': 4,
  'discipline_count': 5,
  'total_lawsuit_settlements': '10000000.00',
  'current_salary': 100000,
  'percentiles': [
    {
      'id': 2,
      'year': 2001,
      'percentile_trr': '0.049',
      'percentile_allegation': '43.233',
    },
    {
      'id': 2,
      'year': 2002,
      'percentile_allegation': '43.233',
      'percentile_allegation_civilian': '0.3',
      'percentile_allegation_internal': '0.023',
    },
    {
      'id': 2,
      'year': 2017,
      'percentile_allegation': '32.102',
    },
  ],
};

export const officerPageCmsData = {
  fields: [
    RichTextFieldFactory.build({ name: 'triangle_description' }, { blockTexts: ['triangle description'] }),
    RichTextFieldFactory.build({ name: 'triangle_sub_description' }, { blockTexts: ['triangle sub description'] }),
    RichTextFieldFactory.build({ name: 'scale_description' }, { blockTexts: ['scale description'] }),
    RichTextFieldFactory.build({ name: 'scale_sub_description' }, { blockTexts: ['scale sub description'] }),
    RichTextFieldFactory.build({ name: 'no_data_explain_text' }, { blockTexts: ['no data explain text'] }),
  ],
  meta: {},
};
