export const officerData = {
  'id': 1,
  'full_name': 'Bernadette Kelly',
  'unit': {
    'id': 1,
    'unit_name': '001',
    'description': 'District 001',
  },
  'date_of_appt': '2015-09-23',
  'rank': 'Police Officer',
  'race': 'White',
  'badge': '12345',
  'historic_badges': ['54321', '56789'],
  'gender': 'Male',
  'birth_year': 1963,
  'allegation_count': 1,
  'percentile_allegation': '2.0000',
  'percentile_trr': '7.9000',
  'trr_count': '5',
  'major_award_count': 19,
  'honorable_mention_count': 3,
  'sustained_count': 4,
  'discipline_count': 5,
  'civilian_compliment_count': 6,
  'current_salary': 100000,
  'honorable_mention_percentile': '79.8700',
  'percentiles': [
    {
      'id': 1,
      'year': 2001,
      'percentile_trr': '0.049',
      'percentile_allegation': '43.233',
    },
    {
      'id': 1,
      'year': 2002,
      'percentile_allegation': '43.233',
      'percentile_allegation_civilian': '0.3',
      'percentile_allegation_internal': '0.023',
    },
    {
      'id': 1,
      'year': 2012,
      'percentile_trr': '0.049',
      'percentile_allegation': '43.233',
      'percentile_allegation_civilian': '0.3',
      'percentile_allegation_internal': '0.023',
    },
    {
      'id': 1,
      'year': 2013,
      'percentile_trr': '0.049',
      'percentile_allegation': '43.233',
      'percentile_allegation_civilian': '22.10',
      'percentile_allegation_internal': '0.023',
    },
    {
      'id': 1,
      'year': 2014,
      'percentile_trr': '0.049',
      'percentile_allegation': '43.233',
      'percentile_allegation_civilian': '10.10',
      'percentile_allegation_internal': '0.023',
    },
    {
      'id': 1,
      'year': 2015,
      'percentile_trr': '66.046',
      'percentile_allegation': '43.233',
      'percentile_allegation_civilian': '75.065',
      'percentile_allegation_internal': '0.022',
    },
    {
      'id': 1,
      'year': 2016,
      'percentile_trr': '66.044',
      'percentile_allegation': '32.102',
      'percentile_allegation_civilian': '59.468',
      'percentile_allegation_internal': '0.021',
    },
    {
      'id': 1,
      'year': 2017,
      'percentile_allegation': '32.102',
    },
  ],
};
