export const lawsuitData = {
  'case_no': '00-L-5230',
  summary: 'Hutchinson was shot and killed outside a bar near the Addison Red Line stop.',
  'primary_cause': 'EXCESSIVE FORCE/MINOR',
  address: '200 E. Chicago Ave., Chicago IL',
  'incident_date': '2015-10-28',
  plaintiffs: [
    {
      name: 'Sharon Ambielli',
    },
    {
      name: 'Kevin Vodak',
    },
  ],
  officers: [
    {
      'percentile_allegation': '59.5430',
      'percentile_trr': '49.1036',
      'percentile_allegation_civilian': '47.6380',
      'percentile_allegation_internal': '0.0000',
      id: 1,
      'full_name': 'Joseph Nega',
      'allegation_count': 12,
      'sustained_count': 0,
      'birth_year': 1964,
      race: 'White',
      gender: 'Male',
      rank: 'Detective',
      'lawsuit_count': 3,
      'lawsuit_payment': '7500022500.00',
    },
    {
      'percentile_allegation': '34.6987',
      'percentile_trr': '67.9110',
      'percentile_allegation_civilian': '43.9207',
      'percentile_allegation_internal': '0.0000',
      id: 2,
      'full_name': 'Robert Rose',
      'allegation_count': 4,
      'sustained_count': 0,
      'birth_year': 1976,
      race: 'White',
      gender: 'Male',
      rank: 'Detective',
      'lawsuit_count': 3,
      'lawsuit_payment': '7500022500.00',
    },
    {
      'percentile_allegation': '0.0000',
      'percentile_trr': '0.0000',
      'percentile_allegation_civilian': '0.0000',
      'percentile_allegation_internal': '0.0000',
      id: 3,
      'full_name': 'David Lavin',
      'allegation_count': 0,
      'sustained_count': 0,
      'birth_year': 1967,
      race: 'White',
      gender: 'Male',
      rank: '',
      'lawsuit_count': 3,
      'lawsuit_payment': '7500022500.00',
    },
    {
      id: 4,
      'full_name': 'John Keiken',
      'allegation_count': 0,
      'sustained_count': 0,
      'birth_year': 1948,
      race: 'White',
      gender: 'Male',
      rank: '',
      'lawsuit_count': 1,
      'lawsuit_payment': '2500007500.00',
    },
    {
      id: 5,
      'full_name': 'Paul Tasch',
      'allegation_count': 0,
      'sustained_count': 0,
      'birth_year': 1924,
      race: 'White',
      gender: 'Male',
      rank: '',
      'lawsuit_count': 2,
      'lawsuit_payment': '5000015000.00',
    },
    {
      'percentile_allegation': '85.5260',
      'percentile_trr': '67.9110',
      'percentile_allegation_civilian': '88.5838',
      'percentile_allegation_internal': '0.0000',
      id: 6,
      'full_name': 'Kevin Stoll',
      'allegation_count': 24,
      'sustained_count': 0,
      'birth_year': 1968,
      race: 'White',
      gender: 'Male',
      rank: 'Detective',
      'lawsuit_count': 3,
      'lawsuit_payment': '7500022500.00',
    },
    {
      'percentile_allegation': '50.8846',
      'percentile_trr': '0.0000',
      'percentile_allegation_civilian': '47.6380',
      'percentile_allegation_internal': '0.0000',
      id: 7,
      'full_name': 'Faizullah Khan',
      'allegation_count': 9,
      'sustained_count': 0,
      'birth_year': 1967,
      race: 'Asian/Pacific',
      gender: 'Male',
      rank: 'Detective',
      'lawsuit_count': 3,
      'lawsuit_payment': '7500022500.00',
    },
    {
      id: 8,
      'full_name': 'L Hippert',
      'allegation_count': 0,
      'sustained_count': 0,
      'birth_year': 1936,
      race: 'White',
      gender: 'Male',
      rank: '',
      'lawsuit_count': 3,
      'lawsuit_payment': '7500022500.00',
    },
    {
      'percentile_allegation': '0.0000',
      id: 9,
      'full_name': 'Clarence Williamson',
      'allegation_count': 0,
      'sustained_count': 0,
      'birth_year': 1944,
      race: 'Black',
      gender: 'Male',
      rank: '',
      'lawsuit_count': 1,
      'lawsuit_payment': '2500007500.00',
    },
    {
      id: 10,
      'full_name': 'Trvon Tines',
      'allegation_count': 0,
      'sustained_count': 0,
      'birth_year': 1991,
      race: 'Black',
      gender: 'Male',
      rank: '',
      'lawsuit_count': 2,
      'lawsuit_payment': '5000015000.00',
    },
    {
      'percentile_allegation': '45.6268',
      'percentile_trr': '0.0000',
      'percentile_allegation_civilian': '24.1180',
      'percentile_allegation_internal': '0.0000',
      id: 11,
      'full_name': 'Peter Vetrano',
      'allegation_count': 10,
      'sustained_count': 1,
      'birth_year': 1963,
      race: 'Hispanic',
      gender: 'Male',
      rank: 'Detective',
      'lawsuit_count': 3,
      'lawsuit_payment': '7500022500.00',
    },
    {
      'percentile_allegation': '0.0000',
      'percentile_trr': '0.0000',
      'percentile_allegation_civilian': '0.0000',
      'percentile_allegation_internal': '0.0000',
      id: 12,
      'full_name': 'Kevin Rake',
      'allegation_count': 0,
      'sustained_count': 0,
      'birth_year': 1942,
      race: 'White',
      gender: 'Male',
      rank: '',
      'lawsuit_count': 2,
      'lawsuit_payment': '5000015000.00',
    },
    {
      id: 13,
      'full_name': 'Antonio Ramirez',
      'allegation_count': 0,
      'sustained_count': 0,
      race: 'Unknown',
      gender: 'Male',
      rank: '',
      'lawsuit_count': 2,
      'lawsuit_payment': '5000015000.00',
    },
    {
      'percentile_allegation': '92.1287',
      'percentile_trr': '0.0000',
      'percentile_allegation_civilian': '85.1455',
      'percentile_allegation_internal': '0.0000',
      id: 14,
      'full_name': 'Mark Zawila',
      'allegation_count': 34,
      'sustained_count': 2,
      'birth_year': 1968,
      race: 'White',
      gender: 'Male',
      rank: 'Detective',
      'lawsuit_count': 3,
      'lawsuit_payment': '7500022500.00',
    },
    {
      id: 15,
      'full_name': 'Richard Brandt',
      'allegation_count': 0,
      'sustained_count': 0,
      'birth_year': 1932,
      race: 'White',
      gender: 'Male',
      rank: '',
      'lawsuit_count': 1,
      'lawsuit_payment': '2500007500.00',
    },
    {
      'percentile_allegation': '0.0000',
      id: 16,
      'full_name': 'Hugh Versteegh',
      'allegation_count': 0,
      'sustained_count': 0,
      'birth_year': 1927,
      race: 'White',
      gender: 'Male',
      rank: '',
      'lawsuit_count': 1,
      'lawsuit_payment': '2500007500.00',
    },
    {
      id: 17,
      'full_name': 'Willis Nance',
      'allegation_count': 0,
      'sustained_count': 0,
      'birth_year': 1936,
      race: 'Black',
      gender: 'Male',
      rank: '',
      'lawsuit_count': 2,
      'lawsuit_payment': '5000015000.00',
    },
    {
      id: 18,
      'full_name': 'F Higgins',
      'allegation_count': 0,
      'sustained_count': 0,
      'birth_year': 1923,
      race: 'White',
      gender: 'Male',
      rank: '',
      'lawsuit_count': 1,
      'lawsuit_payment': '2500007500.00',
    },
    {
      'percentile_allegation': '62.1757',
      'percentile_trr': '63.0035',
      'percentile_allegation_civilian': '65.6966',
      'percentile_allegation_internal': '0.0000',
      id: 19,
      'full_name': 'Randall Ryan',
      'allegation_count': 10,
      'sustained_count': 0,
      'birth_year': 1973,
      race: 'White',
      gender: 'Male',
      rank: 'Detective',
      'lawsuit_count': 3,
      'lawsuit_payment': '7500022500.00',
    },
    {
      'percentile_allegation': '72.9166',
      'percentile_trr': '0.0000',
      'percentile_allegation_civilian': '65.6966',
      'percentile_allegation_internal': '0.0000',
      id: 20,
      'full_name': 'Sean Forde',
      'allegation_count': 18,
      'sustained_count': 0,
      'birth_year': 1961,
      race: 'White',
      gender: 'Male',
      rank: 'Detective',
      'lawsuit_count': 3,
      'lawsuit_payment': '7500022500.00',
    },
  ],
  interactions: ['Protest'],
  services: ['On Duty'],
  misconducts: ['Excessive force', 'Racial epithets'],
  outcomes: ['Killed by officer'],
  violences: ['Physical Force'],
  payments: [
    {
      payee: 'Genre Wilson',
      'legal_fees': '2500000000.00',
    },
    {
      payee: 'Lucy Bells',
      settlement: '7500.00',
    },
  ],
  point: {
    lon: -35.5,
    lat: 68.9,
  },
  'total_payments': {
    total: '2500007500.00',
    'total_settlement': '7500.00',
    'total_legal_fees': '2500000000.00',
  },
  attachment: {
    id: '95636',
    title: 'Product all far later exist he author.',
    'file_type': 'document',
    url: 'https://assets.documentcloud.org/documents/6246754/CRID-1086093-CR-COPA-Summary-Report.pdf',
    'preview_image_url': 'https://assets.documentcloud.org/documents/'
      + '6246754/pages/CRID-1086093-CR-COPA-Summary-Report-p1-normal.gif',
  },
};
