export const lawsuitData = {
  'case_no': '00-L-5230',
  summary: 'Pearce was detained and taken into police custody while he was in the Clearing neighborhood. ' +
    'He was charged with reckless conduct even though officers failed to witness misconduct. ' +
    'While at the station, officers threatened him with lockup if he did not identify a marijuana source. ' +
    'After multiple threats, Pearce identified an individual known as "Hitman". Pearce had not purchased any drugs' +
    ' from "Hitman" in four months and identified a gang way between two houses in the Ashburn neighborhood ' +
    'as the last place of purchase. An officer submitted a complaint for search warrant naming Rudy Cantu ' +
    '(a.k.a. "Hitman"). In the search warrant, the officer falsely stated that a cooperative individual had ' +
    'approached them with the information after having bought drugs from "Hitman" approximately 30 times over ' +
    'the past three months at a residence on 84th Place. The officer did not inform the State\'s Attorney\'s ' +
    'Office that Pearce, the cooperative individual, was detained. The next day, the officer sent a second ' +
    'complaint for search warrant. This warrant claimed that Cantu lived in a residence on 78th Place. ' +
    'The officer made false claims that Pearce had purchased drugs from Cantu at this location more than 30 ' +
    'times in the last three months. Pearce was taken to a lock-up and presented before a judge in order to get ' +
    'the warrant approved. Officers told Pearce that if he wanted to get out, he needed to tell the judge that ' +
    'everything on the warrant was true. He was never given the exact details of the warrant\'s content. ' +
    'The judge approved the warrant and Pearce was taken back to lockup. Officers proceeded to execute a ' +
    'search warrant of the residence on 78th Place. Livingstone, 56, and her mother, Manny, 83, had lived at ' +
    'this location for over 30 years. Without showing a warrant, the officers detained both women inside the house ' +
    'for two hours even though Livingstone told the officers that her son was a Chicago Police detective. ' +
    'She proceeded to call her son, who later arrived at the scene. The search was called off.',
  'primary_cause': 'EXCESSIVE FORCE/MINOR',
  address: '200 E. Chicago Ave., Chicago IL',
  location: 'near intersection of N Wavelandand Sheffield',
  'incident_date': '2015-10-28',
  plaintiffs: [
    {
      name: 'Sharon Ambielli',
    },
    {
      name: 'Kevin Vodak',
    },
  ],
  officers: [
    {
      'percentile_allegation': '59.5430',
      'percentile_trr': '49.1036',
      'percentile_allegation_civilian': '47.6380',
      'percentile_allegation_internal': '0.0000',
      id: 1,
      'full_name': 'Joseph Nega',
      'allegation_count': 12,
      'sustained_count': 0,
      'birth_year': 1964,
      race: 'White',
      gender: 'Male',
      rank: 'Detective',
      'lawsuit_count': 3,
      'total_lawsuit_settlements': '7500022500.00',
    },
    {
      'percentile_allegation': '34.6987',
      'percentile_trr': '67.9110',
      'percentile_allegation_civilian': '43.9207',
      'percentile_allegation_internal': '0.0000',
      id: 2,
      'full_name': 'Robert Rose',
      'allegation_count': 4,
      'sustained_count': 0,
      'birth_year': 1976,
      race: 'White',
      gender: 'Male',
      rank: 'Detective',
      'lawsuit_count': 3,
      'total_lawsuit_settlements': '7500022500.00',
    },
    {
      'percentile_allegation': '0.0000',
      'percentile_trr': '0.0000',
      'percentile_allegation_civilian': '0.0000',
      'percentile_allegation_internal': '0.0000',
      id: 3,
      'full_name': 'David Lavin',
      'allegation_count': 0,
      'sustained_count': 0,
      'birth_year': 1967,
      race: 'White',
      gender: 'Male',
      rank: '',
      'lawsuit_count': 3,
      'total_lawsuit_settlements': '7500022500.00',
    },
    {
      id: 4,
      'full_name': 'John Keiken',
      'allegation_count': 0,
      'sustained_count': 0,
      'birth_year': 1948,
      race: 'White',
      gender: 'Male',
      rank: '',
      'lawsuit_count': 1,
      'total_lawsuit_settlements': '2500007500.00',
    },
    {
      id: 5,
      'full_name': 'Paul Tasch',
      'allegation_count': 0,
      'sustained_count': 0,
      'birth_year': 1924,
      race: 'White',
      gender: 'Male',
      rank: '',
      'lawsuit_count': 2,
      'total_lawsuit_settlements': '5000015000.00',
    },
    {
      'percentile_allegation': '85.5260',
      'percentile_trr': '67.9110',
      'percentile_allegation_civilian': '88.5838',
      'percentile_allegation_internal': '0.0000',
      id: 6,
      'full_name': 'Kevin Stoll',
      'allegation_count': 24,
      'sustained_count': 0,
      'birth_year': 1968,
      race: 'White',
      gender: 'Male',
      rank: 'Detective',
      'lawsuit_count': 3,
      'total_lawsuit_settlements': '7500022500.00',
    },
    {
      'percentile_allegation': '50.8846',
      'percentile_trr': '0.0000',
      'percentile_allegation_civilian': '47.6380',
      'percentile_allegation_internal': '0.0000',
      id: 7,
      'full_name': 'Faizullah Khan',
      'allegation_count': 9,
      'sustained_count': 0,
      'birth_year': 1967,
      race: 'Asian/Pacific',
      gender: 'Male',
      rank: 'Detective',
      'lawsuit_count': 3,
      'total_lawsuit_settlements': '7500022500.00',
    },
    {
      id: 8,
      'full_name': 'L Hippert',
      'allegation_count': 0,
      'sustained_count': 0,
      'birth_year': 1936,
      race: 'White',
      gender: 'Male',
      rank: '',
      'lawsuit_count': 3,
      'total_lawsuit_settlements': '7500022500.00',
    },
    {
      'percentile_allegation': '0.0000',
      id: 9,
      'full_name': 'Clarence Williamson',
      'allegation_count': 0,
      'sustained_count': 0,
      'birth_year': 1944,
      race: 'Black',
      gender: 'Male',
      rank: '',
      'lawsuit_count': 1,
      'total_lawsuit_settlements': '2500007500.00',
    },
    {
      id: 10,
      'full_name': 'Trvon Tines',
      'allegation_count': 0,
      'sustained_count': 0,
      'birth_year': 1991,
      race: 'Black',
      gender: 'Male',
      rank: '',
      'lawsuit_count': 2,
      'total_lawsuit_settlements': '5000015000.00',
    },
    {
      'percentile_allegation': '45.6268',
      'percentile_trr': '0.0000',
      'percentile_allegation_civilian': '24.1180',
      'percentile_allegation_internal': '0.0000',
      id: 11,
      'full_name': 'Peter Vetrano',
      'allegation_count': 10,
      'sustained_count': 1,
      'birth_year': 1963,
      race: 'Hispanic',
      gender: 'Male',
      rank: 'Detective',
      'lawsuit_count': 3,
      'total_lawsuit_settlements': '7500022500.00',
    },
    {
      'percentile_allegation': '0.0000',
      'percentile_trr': '0.0000',
      'percentile_allegation_civilian': '0.0000',
      'percentile_allegation_internal': '0.0000',
      id: 12,
      'full_name': 'Kevin Rake',
      'allegation_count': 0,
      'sustained_count': 0,
      'birth_year': 1942,
      race: 'White',
      gender: 'Male',
      rank: '',
      'lawsuit_count': 2,
      'total_lawsuit_settlements': '5000015000.00',
    },
    {
      id: 13,
      'full_name': 'Antonio Ramirez',
      'allegation_count': 0,
      'sustained_count': 0,
      race: 'Unknown',
      gender: 'Male',
      rank: '',
      'lawsuit_count': 2,
      'total_lawsuit_settlements': '5000015000.00',
    },
    {
      'percentile_allegation': '92.1287',
      'percentile_trr': '0.0000',
      'percentile_allegation_civilian': '85.1455',
      'percentile_allegation_internal': '0.0000',
      id: 14,
      'full_name': 'Mark Zawila',
      'allegation_count': 34,
      'sustained_count': 2,
      'birth_year': 1968,
      race: 'White',
      gender: 'Male',
      rank: 'Detective',
      'lawsuit_count': 3,
      'total_lawsuit_settlements': '7500022500.00',
    },
    {
      id: 15,
      'full_name': 'Richard Brandt',
      'allegation_count': 0,
      'sustained_count': 0,
      'birth_year': 1932,
      race: 'White',
      gender: 'Male',
      rank: '',
      'lawsuit_count': 1,
      'total_lawsuit_settlements': '2500007500.00',
    },
    {
      'percentile_allegation': '0.0000',
      id: 16,
      'full_name': 'Hugh Versteegh',
      'allegation_count': 0,
      'sustained_count': 0,
      'birth_year': 1927,
      race: 'White',
      gender: 'Male',
      rank: '',
      'lawsuit_count': 1,
      'total_lawsuit_settlements': '2500007500.00',
    },
    {
      id: 17,
      'full_name': 'Willis Nance',
      'allegation_count': 0,
      'sustained_count': 0,
      'birth_year': 1936,
      race: 'Black',
      gender: 'Male',
      rank: '',
      'lawsuit_count': 2,
      'total_lawsuit_settlements': '5000015000.00',
    },
    {
      id: 18,
      'full_name': 'F Higgins',
      'allegation_count': 0,
      'sustained_count': 0,
      'birth_year': 1923,
      race: 'White',
      gender: 'Male',
      rank: '',
      'lawsuit_count': 1,
      'total_lawsuit_settlements': '2500007500.00',
    },
    {
      'percentile_allegation': '62.1757',
      'percentile_trr': '63.0035',
      'percentile_allegation_civilian': '65.6966',
      'percentile_allegation_internal': '0.0000',
      id: 19,
      'full_name': 'Randall Ryan',
      'allegation_count': 10,
      'sustained_count': 0,
      'birth_year': 1973,
      race: 'White',
      gender: 'Male',
      rank: 'Detective',
      'lawsuit_count': 3,
      'total_lawsuit_settlements': '7500022500.00',
    },
    {
      'percentile_allegation': '72.9166',
      'percentile_trr': '0.0000',
      'percentile_allegation_civilian': '65.6966',
      'percentile_allegation_internal': '0.0000',
      id: 20,
      'full_name': 'Sean Forde',
      'allegation_count': 18,
      'sustained_count': 0,
      'birth_year': 1961,
      race: 'White',
      gender: 'Male',
      rank: 'Detective',
      'lawsuit_count': 3,
      'total_lawsuit_settlements': '7500022500.00',
    },
  ],
  interactions: ['Protest'],
  services: ['On Duty'],
  misconducts: ['Excessive force', 'Racial epithets'],
  outcomes: ['Killed by officer'],
  violences: ['Physical Force'],
  payments: [
    {
      payee: 'Genre Wilson',
      'legal_fees': '2500000000.00',
    },
    {
      payee: 'Lucy Bells',
      settlement: '7500.00',
    },
  ],
  point: {
    lon: -35.5,
    lat: 68.9,
  },
  'total_payments': '2500007500.00',
  'total_settlement': '7500.00',
  'total_legal_fees': '2500000000.00',
  attachment: {
    id: '95636',
    title: 'Product all far later exist he author.',
    'file_type': 'document',
    url: 'https://assets.documentcloud.org/documents/6246754/CRID-1086093-CR-COPA-Summary-Report.pdf',
    'preview_image_url': 'https://assets.documentcloud.org/documents/'
      + '6246754/pages/CRID-1086093-CR-COPA-Summary-Report-p1-normal.gif',
  },
};
